import { describe, expect, it } from "vitest";
import {
  createTransactionSchema,
  payAllTransactionSchema,
  payTransactionSchema,
  validateBody,
} from "@/lib/validations";

describe("transaction request contracts", () => {
  it("accepts a normal paid sale payload used by POST /api/transactions", () => {
    const result = validateBody(createTransactionSchema, {
      customerId: 1,
      items: [{ productTypeId: 1, quantity: 10, unitPrice: 100 }],
      paid: -1,
      status: "paid",
      saleDate: "2026-03-26",
      saleTime: "10:00:00",
      bagReturns: [],
    });

    expect(result).toEqual({
      data: expect.objectContaining({
        customerId: 1,
        items: [{ productTypeId: 1, quantity: 10, unitPrice: 100 }],
        paid: -1,
        status: "paid",
        saleDate: "2026-03-26",
        saleTime: "10:00:00",
        bagReturns: [],
      }),
    });
  });

  it("accepts bag-return-only sales because bag ledger writes are valid transactions", () => {
    const result = validateBody(createTransactionSchema, {
      customerId: 1,
      items: [],
      saleDate: "2026-03-26",
      saleTime: "10:00:00",
      bagReturns: [{ productTypeId: 2, quantity: 3 }],
    });

    expect(result).toEqual({
      data: expect.objectContaining({
        customerId: 1,
        items: [],
        bagReturns: [{ productTypeId: 2, quantity: 3 }],
      }),
    });
  });

  it("rejects transaction creates with no sale items and no bag returns", () => {
    const result = validateBody(createTransactionSchema, {
      customerId: 1,
      items: [],
      saleDate: "2026-03-26",
      saleTime: "10:00:00",
      bagReturns: [],
    });

    expect(result).toEqual({
      error: "items: ต้องมีรายการขาย หรือคืนถุงอย่างน้อย 1 รายการ",
    });
  });

  it("requires a real transfer reference for invoice-credit writes", () => {
    const result = validateBody(createTransactionSchema, {
      customerId: 1,
      items: [{ productTypeId: 1, quantity: 10, unitPrice: 100 }],
      transactionType: "transfer_out",
      transferRef: "bad-ref",
      saleDate: "2026-03-26",
      saleTime: "10:00:00",
    });

    expect(result).toEqual({
      error: "transferRef: รหัสโอนต้องเป็นรูปแบบ TRF-YYYYMMDD-###",
    });
  });

  it("accepts invoice-credit writes with the transfer ref shape generated by the route", () => {
    const result = validateBody(createTransactionSchema, {
      customerId: 1,
      items: [{ productTypeId: 1, quantity: 10, unitPrice: 100 }],
      transactionType: "transfer_out",
      transferRef: "TRF-20260326-001",
      saleDate: "2026-03-26",
      saleTime: "10:00:00",
    });

    expect(result).toEqual({
      data: expect.objectContaining({
        transactionType: "transfer_out",
        transferRef: "TRF-20260326-001",
      }),
    });
  });

  it("matches the real payment adjustment contract: zero is invalid, reversals are valid", () => {
    expect(validateBody(payTransactionSchema, { id: 77, action: "payment", amount: 0 }))
      .toEqual({ error: "amount: จำนวนเงินต้องไม่เป็น 0" });

    expect(validateBody(payTransactionSchema, { id: 77, action: "payment", amount: -500 }))
      .toEqual({
        data: { id: 77, action: "payment", amount: -500 },
      });
  });

  it("matches the real pay-all contract used by PUT /api/transactions", () => {
    expect(validateBody(payAllTransactionSchema, { action: "payAll", customerId: 9 }))
      .toEqual({
        data: { action: "payAll", customerId: 9 },
      });

    expect(validateBody(payAllTransactionSchema, { action: "payAll", customerId: 0 }))
      .toEqual({ error: "customerId: Too small: expected number to be >0" });
  });
});
