import {
  runDefaultMigrationAction,
  runInitFactoryAction,
  runUploadAction,
  runV5Action,
} from "./actions-bootstrap";
import {
  runCleanupLegacyItemsWindowAction,
  runResetSequencesAction,
  runWipeFactoryDataAction,
  runWipeTransactionsDataAction,
  runWipeTransactionsWindowAction,
} from "./actions-destructive";
import {
  runCleanupLegacyPricesAction,
  runMigratePricesAction,
  runMigrateProductsAction,
  runRenameLegacyProductsAction,
  runRolloutProductTaxonomyAction,
  runSeedBillCounterAction,
  runSyncSiProductsToBearingAction,
} from "./actions-product";
import { runCheckProductsAction, runStatusAction } from "./actions-read-only";
import type { MigrateActionDefinition } from "./types";

export const MIGRATE_ACTIONS: MigrateActionDefinition[] = [
  {
    name: "status",
    method: "GET",
    externalAction: null,
    factoryScope: "none",
    dbTarget: "main",
    mutationType: "read-only",
    requiresConfirmation: false,
    supportsDryRun: false,
    dryRunMode: "disabled",
    failureMode: "single-db-transactional",
    handler: async () => runStatusAction(),
  },
  {
    name: "check-products",
    method: "GET",
    externalAction: "check-products",
    factoryScope: "single",
    dbTarget: "factory",
    mutationType: "read-only",
    requiresConfirmation: false,
    supportsDryRun: false,
    dryRunMode: "disabled",
    failureMode: "single-db-transactional",
    handler: runCheckProductsAction,
  },
  {
    name: "rename-legacy-products",
    method: "GET",
    externalAction: "rename-legacy-products",
    factoryScope: "single",
    dbTarget: "factory",
    mutationType: "read-only",
    requiresConfirmation: false,
    supportsDryRun: false,
    dryRunMode: "disabled",
    failureMode: "single-db-transactional",
    handler: runRenameLegacyProductsAction,
  },
  {
    name: "v5",
    method: "POST",
    externalAction: "v5",
    factoryScope: "all",
    dbTarget: "both",
    mutationType: "additive",
    requiresConfirmation: false,
    supportsDryRun: false,
    dryRunMode: "disabled",
    failureMode: "multi-step-best-effort",
    handler: async () => runV5Action(),
  },
  {
    name: "migrate-products",
    method: "POST",
    externalAction: "migrate-products",
    factoryScope: "single",
    dbTarget: "factory",
    mutationType: "additive",
    requiresConfirmation: false,
    supportsDryRun: true,
    dryRunMode: "query-opt-in",
    failureMode: "single-db-transactional",
    handler: runMigrateProductsAction,
  },
  {
    name: "rollout-product-taxonomy",
    method: "POST",
    externalAction: "rollout-product-taxonomy",
    factoryScope: "single",
    dbTarget: "factory",
    mutationType: "additive",
    requiresConfirmation: false,
    supportsDryRun: false,
    dryRunMode: "disabled",
    failureMode: "single-db-transactional",
    handler: runRolloutProductTaxonomyAction,
  },
  {
    name: "seed-bill-counter",
    method: "POST",
    externalAction: "seed-bill-counter",
    factoryScope: "single",
    dbTarget: "factory",
    mutationType: "additive",
    requiresConfirmation: false,
    supportsDryRun: false,
    dryRunMode: "disabled",
    failureMode: "single-db-transactional",
    handler: runSeedBillCounterAction,
  },
  {
    name: "rename-legacy-products",
    method: "POST",
    externalAction: "rename-legacy-products",
    factoryScope: "single",
    dbTarget: "factory",
    mutationType: "additive",
    requiresConfirmation: false,
    supportsDryRun: true,
    dryRunMode: "query-opt-in",
    failureMode: "single-db-transactional",
    handler: runRenameLegacyProductsAction,
  },
  {
    name: "sync-si-products-to-bearing",
    method: "POST",
    externalAction: "sync-si-products-to-bearing",
    factoryScope: "multiple",
    dbTarget: "factory",
    mutationType: "additive",
    requiresConfirmation: false,
    supportsDryRun: true,
    dryRunMode: "query-opt-in",
    failureMode: "multi-step-best-effort",
    handler: runSyncSiProductsToBearingAction,
  },
  {
    name: "migrate-prices",
    method: "POST",
    externalAction: "migrate-prices",
    factoryScope: "single",
    dbTarget: "factory",
    mutationType: "additive",
    requiresConfirmation: false,
    supportsDryRun: false,
    dryRunMode: "disabled",
    failureMode: "single-db-transactional",
    handler: runMigratePricesAction,
  },
  {
    name: "cleanup-legacy-prices",
    method: "POST",
    externalAction: "cleanup-legacy-prices",
    factoryScope: "single",
    dbTarget: "factory",
    mutationType: "destructive",
    requiresConfirmation: false,
    supportsDryRun: false,
    dryRunMode: "disabled",
    failureMode: "irreversible",
    handler: runCleanupLegacyPricesAction,
  },
  {
    name: "wipe-factory-data",
    method: "POST",
    externalAction: "wipe-factory-data",
    factoryScope: "single",
    dbTarget: "factory",
    mutationType: "destructive",
    requiresConfirmation: "WIPE_FACTORY_DATA",
    supportsDryRun: false,
    dryRunMode: "disabled",
    failureMode: "irreversible",
    handler: runWipeFactoryDataAction,
  },
  {
    name: "wipe-transactions-data",
    method: "POST",
    externalAction: "wipe-transactions-data",
    factoryScope: "single",
    dbTarget: "factory",
    mutationType: "destructive",
    requiresConfirmation: "WIPE_TRANSACTIONS_DATA",
    supportsDryRun: false,
    dryRunMode: "disabled",
    failureMode: "irreversible",
    handler: runWipeTransactionsDataAction,
  },
  {
    name: "wipe-transactions-window",
    method: "POST",
    externalAction: "wipe-transactions-window",
    factoryScope: "single",
    dbTarget: "factory",
    mutationType: "destructive",
    requiresConfirmation: "WIPE_TRANSACTIONS_WINDOW",
    supportsDryRun: false,
    dryRunMode: "disabled",
    failureMode: "single-db-transactional",
    handler: runWipeTransactionsWindowAction,
  },
  {
    name: "cleanup-legacy-items-window",
    method: "POST",
    externalAction: "cleanup-legacy-items-window",
    factoryScope: "single",
    dbTarget: "factory",
    mutationType: "destructive",
    requiresConfirmation: "CLEANUP_LEGACY_ITEMS_WINDOW",
    supportsDryRun: true,
    dryRunMode: "query-opt-out",
    failureMode: "single-db-transactional",
    handler: runCleanupLegacyItemsWindowAction,
  },
  {
    name: "upload",
    method: "POST",
    externalAction: "upload",
    factoryScope: "single",
    dbTarget: "factory",
    mutationType: "additive",
    requiresConfirmation: false,
    supportsDryRun: false,
    dryRunMode: "disabled",
    failureMode: "multi-step-best-effort",
    handler: runUploadAction,
  },
  {
    name: "reset-sequences",
    method: "POST",
    externalAction: "reset-sequences",
    factoryScope: "single",
    dbTarget: "factory",
    mutationType: "destructive",
    requiresConfirmation: false,
    supportsDryRun: false,
    dryRunMode: "disabled",
    failureMode: "single-db-transactional",
    handler: runResetSequencesAction,
  },
  {
    name: "init-factory",
    method: "POST",
    externalAction: "init-factory",
    factoryScope: "single",
    dbTarget: "factory",
    mutationType: "additive",
    requiresConfirmation: false,
    supportsDryRun: false,
    dryRunMode: "disabled",
    failureMode: "multi-step-best-effort",
    handler: runInitFactoryAction,
  },
  {
    name: "default-migration",
    method: "POST",
    externalAction: null,
    factoryScope: "none",
    dbTarget: "main",
    mutationType: "additive",
    requiresConfirmation: false,
    supportsDryRun: false,
    dryRunMode: "disabled",
    failureMode: "multi-step-best-effort",
    handler: async () => runDefaultMigrationAction(),
  },
];

export function findMigrateAction(
  method: "GET" | "POST",
  externalAction: string | null
): MigrateActionDefinition | null {
  return (
    MIGRATE_ACTIONS.find(
      (action) => action.method === method && action.externalAction === externalAction
    ) ?? null
  );
}
